# Generated by Django 5.0.7 on 2024-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('esal', models.IntegerField()),
                ('eaddr', models.CharField(max_length=30)),
            ],
        ),
    ]
